server:
  port: 8701

spring:
  application:
    name: redis-test-controller
    version: 1.0.0
  redis:
    host: 62.234.131.125
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        #最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0